# docker-compose.prod.yml
# Michael Cole
# 
# -Production- Docker Compose file
# Run with `docker-compose -f docker-compose.prod.yml up -d --build`
# ------------------------------------------------------------------

version: '3'

services:

  flask:
    container_name: app
    build: 
      context: ./prosperwooddesigns
      dockerfile: app.dockerfile
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    expose:
      - 5000
    env_file:
      - ./prosperwooddesigns.env
      - ./prosperwooddesigns.secrets.env
    environment:
      - FLASK_ENV=production
    depends_on: 
      - postgres

  postgres:
    container_name: db
    image: postgres:10.4-alpine
    restart: always
    env_file:
      - ./prosperwooddesigns.env
      - ./prosperwooddesigns.secrets.env
    volumes:
      - data_prod:/var/lib/postgresql/data/

  pgbackups3:
    container_name: db_backups
    image: schickling/postgres-backup-s3
    links:
      - postgres
    env_file:
      - ./prosperwooddesigns.env
      - ./prosperwooddesigns.secrets.env

  nginx:
    container_name: server
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on: 
      - flask
      - postgres

volumes:
  data_prod:
