# docker-compose.yml
# Michael Cole
# 
# -Development- Docker Compose file
# ----------------------------------

version: '3'

services:

  flask:
    container_name: app
    build: 
      context: ./prosperwooddesigns
      dockerfile: app.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./prosperwooddesigns:/prosperwooddesigns"
    env_file:
      - ./prosperwooddesigns.env
      - ./prosperwooddesigns.secrets.env
    environment:
      - FLASK_ENV=development
    depends_on: 
      - postgres

  postgres:
    container_name: db
    image: postgres:13-alpine
    env_file:
      - ./prosperwooddesigns.env
      - ./prosperwooddesigns.secrets.env
    volumes:
      - data_dev:/var/lib/postgresql/data/

volumes:
  data_dev:
