version: '3'

services:

  app:
    build: 
      context: ./prosperwooddesigns
      dockerfile: app.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./prosperwooddesigns:/prosperwooddesigns"
    env_file:
      - ./prosperwooddesigns.env