# docker-compose.prod.yml
# Michael Cole
# 
# -Production- Docker Compose file
# ----------------------------------

version: '3'

services:

  flask:
    container_name: app
    build: 
      context: ./prosperwooddesigns
      dockerfile: app.dockerfile
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - "5000:5000"
    env_file:
      - ./prosperwooddesigns.env
      - ./prosperwooddesigns.secrets.env
    environment:
      - FLASK_ENV=production
